# Generated by Django 5.2 on 2026-08-31 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Why',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=70)),
                ('desc_why', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_desc', models.CharField(max_length=1000)),
                ('descraption', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(upload_to='home/')),
                ('logo_black', models.ImageField(upload_to='home/')),
                ('addres', models.CharField(max_length=120)),
                ('phone_numper', models.CharField(max_length=22)),
                ('videoH', models.FileField(blank=True, null=True, upload_to='home_videos/')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('x', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
