# Generated by Django 5.2 on 2025-05-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='videoH',
            field=models.FileField(blank=True, null=True, upload_to='home_videos/'),
        ),
    ]
