# Generated by Django 5.2 on 2025-05-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_videoh'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='logo',
            field=models.ImageField(default=1, upload_to='home/'),
            preserve_default=False,
        ),
    ]
