# Generated by Django 5.2 on 2026-09-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_home_videoh'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='section_logo',
            field=models.ImageField(null=True, upload_to='home/'),
        ),
    ]
