# Generated by Django 5.2 on 2026-09-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_home_section_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='videoH',
        ),
        migrations.AddField(
            model_name='home',
            name='home_background',
            field=models.ImageField(null=True, upload_to='home/'),
        ),
    ]
