# Generated by Django 5.2 on 2025-05-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_home_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='logo_black',
            field=models.ImageField(default=1, upload_to='home/'),
            preserve_default=False,
        ),
    ]
