# Generated by Django 5.1.6 on 2025-02-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirt',
            name='size',
        ),
        migrations.AddField(
            model_name='tshirt',
            name='size',
            field=models.BooleanField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default=True),
        ),
    ]
