# Generated by Django 5.1.6 on 2025-02-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='imge',
            field=models.ImageField(default=1, upload_to='supplies/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tshirt',
            name='size',
            field=models.CharField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
