# Generated by Django 5.1.6 on 2025-02-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_remove_tshirt_size_tshirt_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='size',
        ),
        migrations.AddField(
            model_name='tshirt',
            name='size',
            field=models.ManyToManyField(to='supplies.size'),
        ),
    ]
