# Generated by Django 5.1.6 on 2025-02-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_alter_size_name_remove_tshirt_size_tshirt_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=2, unique=True),
        ),
    ]
