# Generated by Django 5.2 on 2026-08-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imge', models.ImageField(upload_to='Coaches/')),
                ('name', models.CharField(max_length=100)),
                ('Descraption', models.CharField(max_length=50000)),
                ('job_title', models.CharField(choices=[('TEC', 'Technical director'), ('SPO', 'Sports director'), ('ASS', 'Assistant coach')], max_length=3)),
            ],
        ),
    ]
