# Generated by Django 5.2 on 2026-08-31 20:47

import django.core.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('RB', 'Right Back'), ('LB', 'Left Back'), ('CB', 'Center Back'), ('CD', 'Center Defense'), ('RM', 'Right Midfielder'), ('LM', 'Left Midfielder'), ('CM', 'Center Midfielder'), ('RW', 'Right Wing'), ('LW', 'Left Wing'), ('ST', 'Striker')], default='GK', max_length=3, verbose_name='Player Position')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('name', models.CharField(max_length=75)),
                ('imge', models.ImageField(upload_to='players/')),
                ('addres', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone_numper', models.CharField(max_length=22)),
                ('club_name', models.CharField(max_length=50)),
                ('club_flag', models.ImageField(upload_to='players/')),
                ('date_from', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(max_length=20000)),
                ('dribbling', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('passing', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('shooting', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('Pace', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('Defense', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('Physical', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('over_rating', models.IntegerField(blank=True, null=True)),
                ('languages', models.TextField(max_length=50)),
                ('language_strength', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_club_name', models.CharField(max_length=50)),
                ('date_from_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1990)])),
                ('date_to_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1990)])),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description_lastclub', models.TextField(blank=True, max_length=3000, null=True)),
                ('academy_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_from_academy', models.IntegerField(blank=True, null=True)),
                ('date_to_academy', models.IntegerField(blank=True, null=True)),
                ('description_academy', models.TextField(blank=True, max_length=3000, null=True)),
                ('school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_from_school', models.IntegerField(blank=True, null=True)),
                ('date_to_school', models.IntegerField(blank=True, null=True)),
                ('description_school', models.TextField(blank=True, max_length=3000, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='players_videos/')),
            ],
        ),
    ]
