# Generated by Django 5.1.6 on 2025-02-16 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('start_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)])),
                ('end_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)])),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('imge', models.ImageField(upload_to='players/')),
                ('addres', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone_numper', models.CharField(max_length=22)),
                ('club_name', models.CharField(max_length=50)),
                ('date_from', models.DateField()),
                ('description', models.TextField(max_length=20000)),
                ('dribbling', models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)])),
                ('passing', models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)])),
                ('shooting', models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)])),
                ('tackling', models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)])),
                ('languages', models.TextField(max_length=50)),
                ('language_strength', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_club_name', models.CharField(max_length=50)),
                ('date_from1', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)])),
            ],
        ),
    ]
