# Generated by Django 5.1.6 on 2025-02-16 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.AddField(
            model_name='players',
            name='date_from_year',
            field=models.PositiveIntegerField(default=1990, validators=[django.core.validators.MinValueValidator(1990)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='players',
            name='date_to_year',
            field=models.PositiveIntegerField(default=1990, validators=[django.core.validators.MinValueValidator(1990)]),
            preserve_default=False,
        ),
    ]
