# Generated by Django 5.1.6 on 2025-02-16 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_delete_player_players_date_from_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='date_from',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='players',
            name='dribbling',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='players',
            name='passing',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='players',
            name='shooting',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='players',
            name='tackling',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
