# Generated by Django 5.1.6 on 2025-02-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_players_date_from_alter_players_dribbling_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='date_from1',
        ),
        migrations.AddField(
            model_name='players',
            name='academy_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='date_from_academy',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='date_from_school',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='date_to_academy',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='date_to_scshool',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='description_academy',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='description_lastclub',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='description_school',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='school_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
