# Generated by Django 5.1.6 on 2025-02-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_remove_players_date_from1_players_academy_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='date_from_academy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='date_from_school',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='date_to_academy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='date_to_scshool',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
