# Generated by Django 5.1.6 on 2025-02-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_players_date_from_academy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='date_from',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
