# Generated by Django 5.1.6 on 2025-02-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_alter_players_date_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='players_videos/'),
        ),
    ]
