# Generated by Django 5.1.6 on 2025-03-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_players_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='date_to_scshool',
            new_name='date_to_school',
        ),
    ]
