# Generated by Django 5.2 on 2025-05-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_rename_date_to_scshool_players_date_to_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
