# Generated by Django 5.2 on 2025-06-08 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_players_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='tackling',
            new_name='Defense',
        ),
        migrations.AddField(
            model_name='players',
            name='Pace',
            field=models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='players',
            name='Physical',
            field=models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
