# Generated by Django 5.2 on 2025-06-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_rename_tackling_players_defense_players_pace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='over_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
