# Generated by Django 5.2 on 2025-06-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_players_over_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='position',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('RB', 'Right Back'), ('LB', 'Left Back'), ('CB', 'Center Back'), ('CD', 'Center Defense'), ('RM', 'Right Midfielder'), ('LM', 'Left Midfielder'), ('CM', 'Center Midfielder'), ('RW', 'Right Wing'), ('LW', 'Left Wing'), ('ST', 'Striker')], default='GK', max_length=3, verbose_name='Player Position'),
        ),
    ]
