# Generated by Django 5.2 on 2025-06-08 13:01

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_players_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='country',
            field=django_countries.fields.CountryField(default='EG', max_length=2),
            preserve_default=False,
        ),
    ]
