# Generated by Django 5.2 on 2025-06-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_players_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='club_flag',
            field=models.ImageField(default=0, upload_to='players/'),
            preserve_default=False,
        ),
    ]
